language: rust

cache: cargo

rust:
  - stable
  - nightly

env:
  - CRATE=pac/atsamd11c14a
  - CRATE=pac/atsamd21e18a
  - CRATE=pac/atsamd21g18a
  - CRATE=pac/atsamd21j18a
  - CRATE=pac/atsamd51g19a
  - CRATE=pac/atsamd51j19a
  - CRATE=pac/atsamd51j20a
  - CRATE=pac/atsame54p20a
  - CRATE=hal FEATURES="--features=samd11c14a"
  - CRATE=hal FEATURES="--features=samd21g18a"
  - CRATE=hal FEATURES="--features=samd21e18a"
  - CRATE=hal FEATURES="--features=samd21j18a"
  - CRATE=hal FEATURES="--features=samd51g19a"
  - CRATE=hal FEATURES="--features=samd51j19a"
  - CRATE=hal FEATURES="--features=samd51j20a"
  - CRATE=hal FEATURES="--features=same54p20a"
  - CRATE=boards/metro_m0 EXAMPLES="--example=blinky_basic --example=blinky_rtfm" FEATURES="--features=unproven"   
  - CRATE=boards/metro_m4 FEATURES="--features=unproven"
  - CRATE=boards/feather_m0 FEATURES="--features=unproven"
  - CRATE=boards/feather_m4 FEATURES="--features=unproven"
  - CRATE=boards/gemma_m0 FEATURES="--features=unproven"
  - CRATE=boards/itsybitsy_m0 FEATURES="--features=unproven"
  - CRATE=boards/itsybitsy_m4 FEATURES="--features=unproven,usb,use_uart_debug"
  - CRATE=boards/trinket_m0 FEATURES="--features=unproven"
  - CRATE=boards/samd11_bare FEATURES="--features=unproven" BUILDMODE="--release"
  - CRATE=boards/samd21_mini FEATURES="--features=unproven"
  - CRATE=boards/arduino_mkrzero FEATURES="--features=unproven"
  - CRATE=boards/circuit_playground_express FEATURES="--features=unproven"
  - CRATE=boards/sodaq_one FEATURES="--features=unproven"
  - CRATE=boards/sodaq_sara_aff FEATURES="--features=unproven"
  - CRATE=boards/pyportal FEATURES="--features=unproven"
  - CRATE=boards/trellis_m4 FEATURES="--features=keypad-unproven"
  - CRATE=boards/pygamer FEATURES="--features=unproven,usb,ws2812-timer,math"
  - CRATE=boards/pfza_proto1 EXAMPLES="--example=blinky_basic" FEATURES="--features=unproven"
  - CRATE=boards/serpente EXAMPLES="--example=blinky_basic --example=pwm" FEATURES="--features=unproven"

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - rustup target add thumbv6m-none-eabi
  - rustup target add thumbv7em-none-eabihf

script:
  - "cd $CRATE"
  - "cargo check ${EXAMPLES:---examples} $FEATURES $BUILDMODE"

stages:
  - test
