language: rust

cache: cargo

rust:
  - stable
  - nightly

env:
  - CRATE=boards/metro_m0 EXAMPLES="--example=blinky_basic --example=blinky_rtfm"
  - CRATE=boards/metro_m4 FEATURES="--features=unproven"
  - CRATE=boards/feather_m0 FEATURES="--features=unproven"
  - CRATE=boards/feather_m4
  - CRATE=boards/gemma_m0
  - CRATE=boards/itsybitsy_m0
  - CRATE=boards/itsybitsy_m4 FEATURES="--features=unproven,usb,use_uart_debug"
  - CRATE=boards/trinket_m0
  - CRATE=boards/samd11_bare FEATURES="--features=unproven" BUILDMODE="--release"
  - CRATE=boards/samd21_mini
  - CRATE=boards/arduino_mkrzero
  - CRATE=boards/circuit_playground_express
  - CRATE=boards/sodaq_one
  - CRATE=boards/sodaq_sara_aff
  - CRATE=boards/pyportal
  - CRATE=boards/trellis_m4 FEATURES="--features=keypad-unproven"
  - CRATE=boards/pygamer FEATURES="--features=unproven,usb,ws2812-timer,math"
  - CRATE=hal FEATURES="--features=samd21g18a"
  - CRATE=hal FEATURES="--features=samd21e18a"
  - CRATE=hal FEATURES="--features=samd51g19a"
  - CRATE=hal FEATURES="--features=samd51j19a"
  - CRATE=hal FEATURES="--features=samd51j20a"
  - CRATE=pac/atsamd21g18a
  - CRATE=pac/atsamd21e18a
  - CRATE=pac/atsamd51g19a
  - CRATE=pac/atsamd51j19a
  - CRATE=pac/atsamd51j20a

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - rustup target add thumbv6m-none-eabi
  - rustup target add thumbv7em-none-eabihf

script:
  - "cd $CRATE"
  - "cargo build ${EXAMPLES:---examples} $FEATURES $BUILDMODE"

stages:
  - test
